data:extend({
	{
		type = "selection-tool",
		name = "movement-tool",
		icon = "__base__/graphics/icons/tooltips/tooltip-category-steam.png",
		icon_size = 40,
		subgroup = "tool",
		order = "y[movement-tool]",
		stack_size = 1,
		select = { mode = { "any-entity" }, range = 1000, border_color = { 0, 1, 1 }, cursor_box_type = "entity" },
		alt_select = { mode = { "any-entity" }, range = 1000, border_color = { 0, 1, 1 }, cursor_box_type = "entity" },
	},
	{
		type = "custom-input",
		name = "movement-tool-input",
		key_sequence = "control + m",
		consuming = "none",
	},
	{
		type = "shortcut",
		name = "movement-tool",
		action = "lua",
		localised_name = { "item-name.movement-tool" },
		icon = "__base__/graphics/icons/tooltips/tooltip-category-steam.png",
		icon_size = 40,
		small_icon = "__base__/graphics/icons/tooltips/tooltip-category-steam.png",
		small_icon_size = 40,
		order = "y[movement-tool]",
		associated_control_input = "movement-tool-input",
	},
	{
		type = "custom-input",
		name = "move-up",
		key_sequence = "",
		linked_game_control = "move-up",
	},
	{
		type = "custom-input",
		name = "move-right",
		key_sequence = "",
		linked_game_control = "move-right",
	},
	{
		type = "custom-input",
		name = "move-down",
		key_sequence = "",
		linked_game_control = "move-down",
	},
	{
		type = "custom-input",
		name = "move-left",
		key_sequence = "",
		linked_game_control = "move-left",
	},
})
